import { type CharacterDefinition } from "../index.ts";

export const ROME_CHARACTERS: CharacterDefinition[] = [
  {
    id: "SCULPTOR",
    name: "SCULPTOR",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "You start knowing a player. Each night*, you learn the alignment of their most recent nomination.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "VESTAL_VIRGIN",
    name: "VESTAL VIRGIN",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      'You start knowing 1 good & 1 evil character, 1 of which is in-play. When they die, that night you learn 1 good & 1 evil character, 1 of which is in-play. if droisoned/Hannibal, "they" is an arbitrary player',
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "PHYSICIAN",
    name: "PHYSICIAN",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Each night, choose two players (not yourself): they are sober, healthy & get true info tonight. The 1st time the Demon kills one, you learn the Demon type.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "LEGIONARY",
    name: "LEGIONARY",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Each night, you learn how many living evil players are sat clockwise between yourself and a living Legionary. [+0 to +2 Legionary]",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "TRVMPETER",
    name: "TRVMPETER",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Each night*, you learn how many evil players publicly claimed to be Spartacus today.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "MORTICIAN",
    name: "MORTICIAN",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Each night*, if a player died by execution today you learn if either of their living neighbours are evil.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "STANDARD_BEARER",
    name: "STANDARD BEARER",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      'When you are nominated, you may make a unique public statement about the nominator (not yourself). Tonight, you learn if the statement was true. I am the judge of whether or not the statement is "unique" and "about the nominator".',
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "CENTVRION",
    name: "CENTVRION",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "If you nominate & execute a living player, their team loses. You are safe from the Demon. If you publicly claimed to be Spartacus today, you are drunk until dawn.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "MERCHANT",
    name: "MERCHANT",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Once per game, at night, choose to learn the characters of players that have nominated you.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "GLADIATOR",
    name: "GLADIATOR",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Once per game, during the day, publicly choose a living player. Tonight, you and they wake & silently play roshambo: whoever loses dies (someone must lose).",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "ACTOR",
    name: "ACTOR",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Once per game, during the day, publicly guess 3 players' character types (not yourself, 1 guess per type). That night, you learn how many you got correct.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "BLACKSMITH",
    name: "BLACKSMITH",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "The 1st time the Demon kills you, you live & gain a not-in-play Townsfolk ability.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "SCHOLAR",
    name: "SCHOLAR",
    edition: "",
    team: "Townsfolk",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "The 1st time you nominate a living Outsider, they immediately become a not-in-play Townsfolk. [+1 Outsider]",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  /* 
  ========================================
  Outsiders
  ========================================
  */

  {
    id: "THE_TWINS",
    name: "THE TWINS",
    edition: "",
    team: "Outsider",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "You start knowing a player: if either of you are executed, all Townsfolk are drunk until dusk tomorrow.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "WINEMAKER",
    name: "WINEMAKER",
    edition: "",
    team: "Outsider",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Your Townsfolk neighbours are drunk, but every other night, you are drunk until dusk, even if you are dead.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "SPARTACVS",
    name: "SPARTACVS",
    edition: "",
    team: "Outsider",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "If an evil player guesses you (once), your team loses. You might register as a Townsfolk; each day, if you did not publicly claim to be Spartacus, you don't.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "BAD_OMEN",
    name: "BAD OMEN",
    edition: "",
    team: "Outsider",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "You do not know you are a Bad Omen. You think you are a Townsfolk, but you receive false information. You might register as evil, even if dead.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  /* 
  ========================================
  Minions
  ========================================
  */

  {
    id: "TEMPTRESS",
    name: "TEMPTRESS",
    edition: "",
    team: "Minion",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "On your 1st night choose two players: they learn that they were chosen. The 1st time one of them dies by execution, the other becomes evil that night.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "HARVSPEX",
    name: "HARVSPEX",
    edition: "",
    team: "Minion",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Each night, choose a player: you learn their character. The 1st player you choose twice in this way, dies. [+ Spartacus]",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "GLYKON",
    name: "GLYKON",
    edition: "",
    team: "Minion",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "You might register as good. Until dawn, players you nominate register as the opposing alignment & if a Townsfolk, are also poisoned.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "AVGVR",
    name: "AVGVR",
    edition: "",
    team: "Minion",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "If a Townsfolk nominates you, they immediately become a Bad Omen.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  /* 
  ========================================
  Demons
  ========================================
  */

  {
    id: "CLEOPATRA",
    name: "CLEOPATRA",
    edition: "",
    team: "Demon",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Each night, choose two players: if they nominate tomorrow, they die that night. Each day, if a good player (Travellers don't count) does not nominate, evil wins.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "CRASSUS",
    name: "CRASSUS",
    edition: "",
    team: "Demon",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Each night*, choose a player: they die. If the 1st Crassus publicly claims to be Spartacus & dies with 5 or more players alive, an evil player becomes Crassus.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "HANNIBAL",
    name: "HANNIBAL",
    edition: "",
    team: "Demon",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "You think you are a good character, but you are not. Minions learn 3 bluffs. Each night*, a player might die. The 1st Hannibal to die, becomes good. [+1 Hannibal]",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
  {
    id: "CAESAR",
    name: "CAESAR",
    edition: "",
    team: "Demon",
    reminders: [],
    setup: false,
    delusional: false,
    ability:
      "Each night*, choose a player: they die. The 1st time an evil player dies by execution, that night, choose an additional player: they die.",
    imageSrc: "",
    firstNight: null,
    otherNight: null,
  },
];
