export type ScriptName =
  | "Trouble Brewing"
  | "Bad Moon Rising"
  | "Sects & Violets"
  | "Catfishing"
  | "Fall of Rome"
  | "No Roles Barred";

export interface ScriptDefinitionLike<T extends string> {
  name: T;
  imageSrc: string;
  characters: { id: string }[];
}
export type ScriptDefinition = ScriptDefinitionLike<ScriptName>;

export const SCRIPTS: ScriptDefinition[] = [
  {
    name: "Trouble Brewing",
    imageSrc:
      "https://wiki.bloodontheclocktower.com/images/a/a1/Logo_trouble_brewing.png",
    characters: [
      { id: "washerwoman" },
      { id: "librarian" },
      { id: "investigator" },
      { id: "chef" },
      { id: "empath" },
      { id: "fortuneteller" },
      { id: "undertaker" },
      { id: "monk" },
      { id: "ravenkeeper" },
      { id: "virgin" },
      { id: "slayer" },
      { id: "soldier" },
      { id: "mayor" },
      { id: "drunk" },
      { id: "butler" },
      { id: "recluse" },
      { id: "saint" },
      { id: "poisoner" },
      { id: "spy" },
      { id: "scarletwoman" },
      { id: "baron" },
      { id: "imp" },
    ],
  },
  {
    name: "Sects & Violets",
    imageSrc:
      "https://wiki.bloodontheclocktower.com/images/4/43/Logo_sects_and_violets.png",
    characters: [
      { id: "clockmaker" },
      { id: "dreamer" },
      { id: "snakecharmer" },
      { id: "mathematician" },
      { id: "flowergirl" },
      { id: "towncrier" },
      { id: "oracle" },
      { id: "savant" },
      { id: "seamstress" },
      { id: "philosopher" },
      { id: "artist" },
      { id: "juggler" },
      { id: "sage" },
      { id: "mutant" },
      { id: "sweetheart" },
      { id: "barber" },
      { id: "klutz" },
      { id: "eviltwin" },
      { id: "witch" },
      { id: "cerenovus" },
      { id: "pithag" },
      { id: "fanggu" },
      { id: "vigormortis" },
      { id: "nodashii" },
      { id: "vortox" },
    ],
  },
  {
    name: "Bad Moon Rising",
    imageSrc:
      "https://wiki.bloodontheclocktower.com/images/1/10/Logo_bad_moon_rising.png",
    characters: [
      { id: "grandmother" },
      { id: "sailor" },
      { id: "chambermaid" },
      { id: "exorcist" },
      { id: "innkeeper" },
      { id: "gambler" },
      { id: "gossip" },
      { id: "courtier" },
      { id: "professor" },
      { id: "minstrel" },
      { id: "tealady" },
      { id: "pacifist" },
      { id: "fool" },
      { id: "goon" },
      { id: "lunatic" },
      { id: "tinker" },
      { id: "moonchild" },
      { id: "godfather" },
      { id: "devilsadvocate" },
      { id: "assassin" },
      { id: "mastermind" },
      { id: "zombuul" },
      { id: "pukka" },
      { id: "shabaloth" },
      { id: "po" },
    ],
  },
  {
    name: "Catfishing",
    imageSrc:
      "https://content.osgnetworks.tv/gameandfishing/content/photos/gaf-RiverMonstersFelsher-Lead-1200x800.jpg",
    characters: [
      { id: "investigator" },
      { id: "chef" },
      { id: "grandmother" },
      { id: "balloonist" },
      { id: "dreamer" },
      { id: "fortuneteller" },
      { id: "snakecharmer" },
      { id: "gambler" },
      { id: "savant" },
      { id: "philosopher" },
      { id: "ravenkeeper" },
      { id: "amnesiac" },
      { id: "cannibal" },
      { id: "drunk" },
      { id: "recluse" },
      { id: "sweetheart" },
      { id: "mutant" },
      { id: "lunatic" },
      { id: "godfather" },
      { id: "cerenovus" },
      { id: "pithag" },
      { id: "widow" },
      { id: "imp" },
      { id: "vigormortis" },
      { id: "fanggu" },
    ],
  },
  {
    name: "Fall of Rome",
    imageSrc: "https://www.bloodstar.xyz/p/AlexS/Fall_of_Rome/_meta.png",
    characters: [
      { id: "sculptor_fall_of_rome" },
      { id: "vestalvirgin_fall_of_rome" },
      { id: "physician_fall_of_rome" },
      { id: "legionary_fall_of_rome" },
      { id: "trumpeter_fall_of_rome" },
      { id: "mortician_fall_of_rome" },
      { id: "standardbearer_fall_of_rome" },
      { id: "centurion1_fall_of_rome" },
      { id: "merchant_fall_of_rome" },
      { id: "gladiator_fall_of_rome" },
      { id: "actor_fall_of_rome" },
      { id: "blacksmith_fall_of_rome" },
      { id: "scholar_fall_of_rome" },
      { id: "thetwins_fall_of_rome" },
      { id: "winemaker_fall_of_rome" },
      { id: "spartacus_fall_of_rome" },
      { id: "badomen_fall_of_rome" },
      { id: "temptress_fall_of_rome" },
      { id: "haruspex_fall_of_rome" },
      { id: "glykon1_fall_of_rome" },
      { id: "augur_fall_of_rome" },
      { id: "cleopatra_fall_of_rome" },
      { id: "crassus_fall_of_rome" },
      { id: "hannibal_fall_of_rome" },
      { id: "caesar_fall_of_rome" },
      { id: "mercenary_fall_of_rome" },
      { id: "architect_fall_of_rome" },
      { id: "sibyl_fall_of_rome" },
      { id: "highpriest1_fall_of_rome" },
      { id: "highpriest2_fall_of_rome" },
      { id: "emperor_fall_of_rome" },
    ],
  },
  // test only
  {
    name: "No Roles Barred",
    imageSrc: "",
    characters: [
      { id: "alchemist" },
      { id: "noble" },
      { id: "pixie" },
      { id: "bountyhunter" },
      { id: "balloonist" },
      { id: "empath" },
      { id: "snakecharmer" },
      { id: "gossip" },
      { id: "amnesiac" },
      { id: "artist" },
      { id: "philosopher" },
      { id: "huntsman" },
      { id: "poppygrower" },
      { id: "goon" },
      { id: "mutant" },
      { id: "damsel" },
      { id: "drunk" },
      { id: "godfather" },
      { id: "poisoner" },
      { id: "fearmonger" },
      { id: "goblin" },
      { id: "boomdandy" },
      { id: "lilmonsta" },
      { id: "legion" },
      { id: "vortox" },
    ],
  },
  {
    name: "Fall of Rome",
    imageSrc: "https://www.bloodstar.xyz/p/AlexS/Fall_of_Rome/_meta.png",
    characters: [
      { id: "sculptor_fall_of_rome" },
      { id: "vestalvirgin_fall_of_rome" },
      { id: "physician_fall_of_rome" },
      { id: "legionary_fall_of_rome" },
      { id: "trumpeter_fall_of_rome" },
      { id: "mortician_fall_of_rome" },
      { id: "standardbearer_fall_of_rome" },
      { id: "centurion1_fall_of_rome" },
      { id: "merchant_fall_of_rome" },
      { id: "gladiator_fall_of_rome" },
      { id: "actor_fall_of_rome" },
      { id: "blacksmith_fall_of_rome" },
      { id: "scholar_fall_of_rome" },
      { id: "thetwins_fall_of_rome" },
      { id: "winemaker_fall_of_rome" },
      { id: "spartacus_fall_of_rome" },
      { id: "badomen_fall_of_rome" },
      { id: "temptress_fall_of_rome" },
      { id: "haruspex_fall_of_rome" },
      { id: "glykon1_fall_of_rome" },
      { id: "augur_fall_of_rome" },
      { id: "cleopatra_fall_of_rome" },
      { id: "crassus_fall_of_rome" },
      { id: "hannibal_fall_of_rome" },
      { id: "caesar_fall_of_rome" },
      { id: "mercenary_fall_of_rome" },
      { id: "architect_fall_of_rome" },
      { id: "sibyl_fall_of_rome" },
      { id: "highpriest1_fall_of_rome" },
      { id: "highpriest2_fall_of_rome" },
      { id: "emperor_fall_of_rome" },
    ],
  },
];

// confirm all roles are valid
export const ALL_ROLES_SCRIPT: ScriptDefinitionLike<string> = {
  name: "all roles",
  imageSrc: "",
  characters: [
    { id: "steward" },
    { id: "knight" },
    { id: "noble" },
    { id: "chef" },
    { id: "investigator" },
    { id: "washerwoman" },
    { id: "clockmaker" },
    { id: "librarian" },
    { id: "grandmother" },
    { id: "shugenja" },
    { id: "pixie" },
    { id: "empath" },
    { id: "sailor" },
    { id: "general" },
    { id: "preacher" },
    { id: "chambermaid" },
    { id: "dreamer" },
    { id: "king" },
    { id: "balloonist" },
    { id: "mathematician" },
    { id: "flowergirl" },
    { id: "oracle" },
    { id: "undertaker" },
    { id: "innkeeper" },
    { id: "gambler" },
    { id: "monk" },
    { id: "lycanthrope" },
    { id: "exorcist" },
    { id: "gossip" },
    { id: "savant" },
    { id: "amnesiac" },
    { id: "juggler" },
    { id: "nightwatchman" },
    { id: "engineer" },
    { id: "artist" },
    { id: "courtier" },
    { id: "slayer" },
    { id: "fisherman" },
    { id: "professor" },
    { id: "seamstress" },
    { id: "philosopher" },
    { id: "huntsman" },
    { id: "soldier" },
    { id: "fool" },
    { id: "alchemist" },
    { id: "pacifist" },
    { id: "sage" },
    { id: "farmer" },
    { id: "magician" },
    { id: "choirboy" },
    { id: "ravenkeeper" },
    { id: "virgin" },
    { id: "minstrel" },
    { id: "cannibal" },
    { id: "atheist" },
    { id: "mayor" },
    { id: "snitch" },
    { id: "butler" },
    { id: "goon" },
    { id: "acrobat" },
    { id: "puzzlemaster" },
    { id: "tinker" },
    { id: "saint" },
    { id: "sweetheart" },
    { id: "recluse" },
    { id: "heretic" },
    { id: "mutant" },
    { id: "damsel" },
    { id: "klutz" },
    { id: "drunk" },
    { id: "golem" },
    { id: "moonchild" },
    { id: "politician" },
    { id: "lunatic" },
    { id: "barber" },
    { id: "widow" },
    { id: "godfather" },
    { id: "poisoner" },
    { id: "harpy" },
    { id: "spy" },
    { id: "witch" },
    { id: "cerenovus" },
    { id: "fearmonger" },
    { id: "psychopath" },
    { id: "assassin" },
    { id: "baron" },
    { id: "mezepheles" },
    { id: "goblin" },
    { id: "vizier" },
    { id: "mastermind" },
    { id: "boomdandy" },
    { id: "marionette" },
    { id: "pukka" },
    { id: "lleech" },
    { id: "imp" },
    { id: "ojo" },
    { id: "shabaloth" },
    { id: "po" },
    { id: "vortox" },
    { id: "vigormortis" },
    { id: "legion" },
    { id: "zombuul" },
    { id: "leviathan" },
    { id: "riot" },
    { id: "scapegoat" },
    { id: "judge" },
    { id: "gardener" },
    { id: "bootlegger" },
    { id: "boffin" },
    { id: "bureaucrat" },
    { id: "fortuneteller" },
    { id: "thief" },
    { id: "gunslinger" },
    { id: "beggar" },
    { id: "tealady" },
    { id: "apprentice" },
    { id: "matron" },
    { id: "bishop" },
    { id: "voudon" },
    { id: "highpriestess" },
    { id: "devilsadvocate" },
    { id: "harlot" },
    { id: "butcher" },
    { id: "fanggu" },
    { id: "towncrier" },
    { id: "eviltwin" },
    { id: "barista" },
    { id: "deviant" },
    { id: "nodashii" },
    { id: "bonecollector" },
    { id: "cultleader" },
    { id: "gangster" },
    { id: "scarletwoman" },
    { id: "alhadikhia" },
    { id: "lilmonsta" },
    { id: "revolutionary" },
    { id: "fiddler" },
    { id: "toymaker" },
    { id: "bountyhunter" },
    { id: "fibbin" },
    { id: "spiritofivory" },
    { id: "hellslibrarian" },
    { id: "djinn" },
    { id: "duchess" },
    { id: "snakecharmer" },
    { id: "pithag" },
    { id: "poppygrower" },
    { id: "sentinel" },
    { id: "doomsayer" },
    { id: "angel" },
    { id: "buddhist" },
    { id: "stormcatcher" },
    { id: "yaggababble" },
    { id: "ferryman" },
    { id: "gnome" },
    { id: "organgrinder" },
    { id: "plaguedoctor" },
    { id: "hatter" },
    { id: "summoner" },
    { id: "kazali" },
    { id: "banshee" },
    { id: "ogre" },
    { id: "alsaahir" },
    { id: "zealot" },
    { id: "lordoftyphon" },
    { id: "xaan" },
    { id: "wizard" },
    { id: "villageidiot" },
    { id: "hermit" },
    { id: "princess" },
    { id: "wraith" },
    { id: "cacklejack" },
    { id: "tor" },
    { id: "bigwig" },
  ],
};
