export type ScriptName =
  | "Trouble Brewing"
  | "Bad Moon Rising"
  | "Sects & Violets"
  | "Catfishing"
  | "🌶️ TB"
  | "No Roles Barred"
  | "Uncertain Death"
  | "Fall of Rome";
export type ScriptDefinition = {
  name: ScriptName;
  imageSrc: string;
  characters: { id: string }[];
};

export const SCRIPTS: ScriptDefinition[] = [
  {
    name: "Trouble Brewing",
    imageSrc:
      "https://wiki.bloodontheclocktower.com/images/a/a1/Logo_trouble_brewing.png",
    characters: [
      { id: "washerwoman" },
      { id: "librarian" },
      { id: "investigator" },
      { id: "chef" },
      { id: "empath" },
      { id: "fortune_teller" },
      { id: "undertaker" },
      { id: "monk" },
      { id: "ravenkeeper" },
      { id: "virgin" },
      { id: "slayer" },
      { id: "soldier" },
      { id: "mayor" },
      { id: "drunk" },
      { id: "butler" },
      { id: "recluse" },
      { id: "saint" },
      { id: "poisoner" },
      { id: "spy" },
      { id: "scarlet_woman" },
      { id: "baron" },
      { id: "imp" },
    ],
  },
  {
    name: "Sects & Violets",
    imageSrc:
      "https://wiki.bloodontheclocktower.com/images/4/43/Logo_sects_and_violets.png",
    characters: [
      { id: "clockmaker" },
      { id: "dreamer" },
      { id: "snake_charmer" },
      { id: "mathematician" },
      { id: "flowergirl" },
      { id: "town_crier" },
      { id: "oracle" },
      { id: "savant" },
      { id: "seamstress" },
      { id: "philosopher" },
      { id: "artist" },
      { id: "juggler" },
      { id: "sage" },
      { id: "mutant" },
      { id: "sweetheart" },
      { id: "barber" },
      { id: "klutz" },
      { id: "evil_twin" },
      { id: "witch" },
      { id: "cerenovus" },
      { id: "pit-hag" },
      { id: "fang_gu" },
      { id: "vigormortis" },
      { id: "no_dashii" },
      { id: "vortox" },
    ],
  },
  {
    name: "Bad Moon Rising",
    imageSrc:
      "https://wiki.bloodontheclocktower.com/images/1/10/Logo_bad_moon_rising.png",
    characters: [
      { id: "grandmother" },
      { id: "sailor" },
      { id: "chambermaid" },
      { id: "exorcist" },
      { id: "innkeeper" },
      { id: "gambler" },
      { id: "gossip" },
      { id: "courtier" },
      { id: "professor" },
      { id: "minstrel" },
      { id: "tea_lady" },
      { id: "pacifist" },
      { id: "fool" },
      { id: "goon" },
      { id: "lunatic" },
      { id: "tinker" },
      { id: "moonchild" },
      { id: "godfather" },
      { id: "devils_advocate" },
      { id: "assassin" },
      { id: "mastermind" },
      { id: "zombuul" },
      { id: "pukka" },
      { id: "shabaloth" },
      { id: "po" },
    ],
  },
  {
    name: "Catfishing",
    imageSrc:
      "https://content.osgnetworks.tv/gameandfishing/content/photos/gaf-RiverMonstersFelsher-Lead-1200x800.jpg",
    characters: [
      { id: "investigator" },
      { id: "chef" },
      { id: "grandmother" },
      { id: "balloonist" },
      { id: "dreamer" },
      { id: "fortune_teller" },
      { id: "snake_charmer" },
      { id: "gambler" },
      { id: "savant" },
      { id: "philosopher" },
      { id: "ravenkeeper" },
      { id: "amnesiac" },
      { id: "cannibal" },
      { id: "drunk" },
      { id: "recluse" },
      { id: "sweetheart" },
      { id: "mutant" },
      { id: "lunatic" },
      { id: "godfather" },
      { id: "cerenovus" },
      { id: "pit-hag" },
      { id: "widow" },
      { id: "imp" },
      { id: "vigormortis" },
      { id: "fang_gu" },
    ],
  },
  {
    name: "🌶️ TB",
    imageSrc:
      "https://i5.walmartimages.com/asr/d84e2293-9320-4867-b0f0-8532b1328cb7_1.2e5f695ebd8d419128c9e7c050de0999.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF",
    characters: [
      { id: "washerwoman" },
      { id: "librarian" },
      { id: "investigator" },
      { id: "chef" },
      { id: "empath" },
      { id: "fortune_teller" },
      { id: "undertaker" },
      { id: "monk" },
      { id: "ravenkeeper" },
      { id: "virgin" },
      { id: "slayer" },
      { id: "soldier" },
      { id: "mayor" },
      { id: "atheist" },
      { id: "drunk" },
      { id: "recluse" },
      { id: "saint" },
      { id: "lunatic" },
      { id: "baron" },
      { id: "poisoner" },
      { id: "scarlet_woman" },
      { id: "spy" },
      { id: "marionette" },
      { id: "imp" },
      { id: "legion" },
    ],
  },
  {
    name: "Uncertain Death",
    imageSrc:
      "https://quotefancy.com/media/wallpaper/1600x900/558572-Buddha-Quote-Life-is-uncertain-death-is-certain.jpg",
    characters: [
      { id: "clockmaker" },
      { id: "grandmother" },
      { id: "librarian" },
      { id: "empath" },
      { id: "fortune_teller" },
      { id: "exorcist" },
      { id: "flowergirl" },
      { id: "oracle" },
      { id: "undertaker" },
      { id: "artist" },
      { id: "slayer" },
      { id: "seamstress" },
      { id: "monk" },
      { id: "lunatic" },
      { id: "mutant" },
      { id: "sweetheart" },
      { id: "recluse" },
      { id: "godfather" },
      { id: "assassin" },
      { id: "scarlet_woman" },
      { id: "marionette" },
      { id: "no_dashii" },
      { id: "pukka" },
    ],
  },
  {
    name: "No Roles Barred",
    imageSrc: "",
    characters: [
      { id: "alchemist" },
      { id: "noble" },
      { id: "pixie" },
      { id: "bounty_hunter" },
      { id: "balloonist" },
      { id: "empath" },
      { id: "snake_charmer" },
      { id: "gossip" },
      { id: "amnesiac" },
      { id: "artist" },
      { id: "philosopher" },
      { id: "huntsman" },
      { id: "poppy_grower" },
      { id: "goon" },
      { id: "mutant" },
      { id: "damsel" },
      { id: "drunk" },
      { id: "godfather" },
      { id: "poisoner" },
      { id: "fearmonger" },
      { id: "goblin" },
      { id: "boomdandy" },
      { id: "lil_monsta" },
      { id: "legion" },
      { id: "vortox" },
    ],
  },
  {
    name: "Fall of Rome",
    imageSrc: "https://www.bloodstar.xyz/p/AlexS/Fall_of_Rome/_meta.png",
    characters: [
      { id: "sculptor_fall_of_rome" },
      { id: "vestalvirgin_fall_of_rome" },
      { id: "physician_fall_of_rome" },
      { id: "legionary_fall_of_rome" },
      { id: "trumpeter_fall_of_rome" },
      { id: "mortician_fall_of_rome" },
      { id: "standardbearer_fall_of_rome" },
      { id: "centurion1_fall_of_rome" },
      { id: "merchant_fall_of_rome" },
      { id: "gladiator_fall_of_rome" },
      { id: "actor_fall_of_rome" },
      { id: "blacksmith_fall_of_rome" },
      { id: "scholar_fall_of_rome" },
      { id: "thetwins_fall_of_rome" },
      { id: "winemaker_fall_of_rome" },
      { id: "spartacus_fall_of_rome" },
      { id: "badomen_fall_of_rome" },
      { id: "temptress_fall_of_rome" },
      { id: "haruspex_fall_of_rome" },
      { id: "glykon1_fall_of_rome" },
      { id: "augur_fall_of_rome" },
      { id: "cleopatra_fall_of_rome" },
      { id: "crassus_fall_of_rome" },
      { id: "hannibal_fall_of_rome" },
      { id: "caesar_fall_of_rome" },
      { id: "mercenary_fall_of_rome" },
      { id: "architect_fall_of_rome" },
      { id: "sibyl_fall_of_rome" },
      { id: "highpriest1_fall_of_rome" },
      { id: "highpriest2_fall_of_rome" },
      { id: "emperor_fall_of_rome" },
    ],
  },
];
